### ISSUE TITLE
Plugin doesn't let me change "date enacted" for statutes

### ISSUE THREAD

**Issue by LightTemplar** [retorquere/zotero-date-from-last-modified#16]
I have items, imported from Europe Commision site as Statutes. Some of them show "date enacted" field as "1970-1-1", which is clearly wrong. If I try to correct the date, it always reverts to "1970-1-1" after 1-2 seconds. 

![Zotero Date enacted](https://github.com/retorquere/zotero-date-from-last-modified/assets/453783/ff6020e0-638c-4247-a586-869612e4f1bc)

After I disabled the add-on, problem was gone.
Imported item with this problem: http://data.europa.eu/eli/reg_impl/2021/1079/oj/eng

Zotero: 6.0.26
Add-on: 0.1.0
OS: Kubuntu 22.04

**Comment by benpla** [comment]
I have this problem, too:
When entering laws, I can enter any date in the "Date Enacted" field. As soon as the cursor leaves the field, the content jumps back to "1970-1-1" after about 1 second.

This happens both when I create an entry manually and when I import automatically. With automatic import, the correct date is applied first (Zotero runs on the second screen) and jumps back to "1970-1-1" after 1 second.

It is not possible to enter a different date at the moment. I have tested all date types before, even the simple year.
This behavior only occurs with the "Statute" type.
