### ISSUE TITLE
It appears to be corrupt, according to Firefox.

### ISSUE THREAD

**Issue by Spirogira** [retorquere/zotero-date-from-last-modified#17]
I'´m getting an error stating Firefox can't install the .xpi as it appears to be corrupt.

**Comment by retorquere** [comment]
Right-click and save the extension instead of left-click it to download. With left-click, Firefox thinks it's a Firefox extension and tries to install it in Firefox instead of zotero.

**Comment by Spirogira** [comment]
Oh, ouch, this was a dumb one! Thank you for the attention.

**Comment by retorquere** [comment]
It hits every Firefox user the first time. It's a stupid error message.
