### ISSUE TITLE
When plug-in is enabled, adding or deleting attached URI links causes them to be triggered

### ISSUE THREAD

**Issue by rwaldspur** [retorquere/zotero-date-from-last-modified#19]
Strangely, when adding or deleting an attached file link, it triggers the file link, causing another application to open.
E.g. If I would have the following link:

obsidian://advanced-uri?vault=ObsV&uid=60dd90b8-e8e8-4401-939d-6b7b0a266ed0

And I either:
select a parent item and then "Attach Link to URI..."
or
delete the attached link that is created...

It triggers the execution of the link and in this case it hands it off to Obsidian.

Reproducability is 100%.
I have removed all plug-ins, as well as disabled Keyboard Maestro macros on my machine.

It could still be some other interaction, but I have not been able to track it down.

Zotero 6.0.26
zotero-date-from-last-modified v0.1.0
macOS 13.4.1

**Comment by retorquere** [comment]
I've just updated the plugin, the previous version did touch the attachments, the latest one does not.

**Comment by rwaldspur** [comment]
Fantastic, it seems to work just fine now.

Thank you.
