### ISSUE TITLE
Europe time format: DD-MM-YYYY

### ISSUE THREAD

**Issue by Mattdejong** [retorquere/zotero-date-from-last-modified#20]
Hey Thank you for your time and effort to keep this project alive. Im loving the plugin.

I have a request. Can you make it possible to add the Europe time format? DD-MM-YYYY. For some reason the format I have now is: YYYY-MM-DD. Don't know if it's a bug or that this is a feature request (because its works as intended)

<img width="352" alt="Scherm­afbeelding 2024-04-23 om 11 21 26" src="https://github.com/retorquere/zotero-date-from-last-modified/assets/44605389/ace25fb4-4150-4b87-b331-447849937dae">
. 

Im using as you suggested and wished for the latest version.

Thanks

**Comment by retorquere** [comment]
I format them this way because they're unambiguous. 02-03-2024 has a locale-dependent meaning whereas 2024-03-02.

**Comment by Mattdejong** [comment]
I see that’s a clever way of coding. So if you put it the right way you can’t be sure anymore which value was the month and which was the day after the conversion in standard format?

but is it possible to do a second conversion? After the succes of the first one?

**Comment by retorquere** [comment]
Possible yes, but desirable AFAIC, no. Zotero will show the date interpretation in your current locale alongside the YYYY-MM-DD format.
